-- DML 중 MERGE 는 과연 트랜잭션 처리가 필요한 지 확인

-- 테이블 복제
CREATE TABLE TB_TEST_M
AS SELECT * FROM employee;

CREATE TABLE TB_EMP_M2
AS SELECT * FROM employee;

INSERT INTO TB_EMP_M2 (EMP_ID, EMP_NAME, EMP_NO, JOB_CODE, SALARY)
VALUES(500, 'IO', '022020-1020330', 'J2', 2000000);

COMMIT;

SELECT COUNT(*) FROM TB_TEST_M; -- 25행
SELECT COUNT(*) FROM TB_EMP_M2; -- 26행

MERGE INTO TB_TEST_M T
USING TB_EMP_M2 E
ON (T.EMP_ID = E.EMP_ID)
WHEN MATCHED THEN   -- 일치하는 데이터가 있을 때 업데이트
UPDATE SET T.SALARY = E.SALARY, T.BONUS = E.BONUS
WHEN NOT MATCHED THEN  -- 일치하는 데이터가 없을 때 추가
INSERT (T.EMP_ID, T.EMP_NO, T.EMP_NAME, T.JOB_CODE, T.SALARY)
VALUES (E.EMP_ID, E.EMP_NO, E.EMP_NAME, E.JOB_CODE, E.SALARY);

ROLLBACK;
--> MERGE 명령어도 트랜잭션 처리가 필요함!